version: '3.8'

services:
  web:
    build: ./app
    ports:
      - "8082:3000" # Changed host port from 8080 to 8081
    environment:
      - DATABASE_URL=postgres://myuser:mypassword@db:5432/mydatabase
      # NODE_ENV: development # Example: if your app uses NODE_ENV
    depends_on:
      - db
    networks:
      - app-net

  db:
    image: postgres:latest
    restart: always # Ensures the DB service attempts to restart if it fails
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydatabase
    volumes:
      - pgdata:/var/lib/postgresql/data # Persist database data in a named volume
    networks:
      - app-net
    ports: # Optional: Expose PostgreSQL port to host for external tools (e.g., pgAdmin)
      - "5432:5432" # Be cautious with exposing DB ports directly in production

  slack-notifier:
    build: ./slack-notifier
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # Mount Docker socket read-only
    environment:
      SLACK_WEBHOOK_URL: "https://hooks.slack.com/services/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"
    logging: # Optional: configure logging for the notifier itself
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  app-net:
    driver: bridge

volumes:
  pgdata: # Defines the named volume for data persistence
